# -*- coding: utf-8 -*-

LANG_ES = {
    "APP_TITLE": "Simulador de Fluidos LBM",
    "BTN_PAUSE": "Pausa",
    "BTN_START": "Inicio",
    "BTN_NEXT_FRAME": "Siguiente Cuadro",
    "BTN_RESET": "Reiniciar",
    "BTN_IMPORT": "Abrir",
    "BTN_EXPORT": "Guardar",
    "BTN_ADVANCED_BARRIER": "Barrera Avanzada",
    "FRAME_BASIC_INFO": "Información Básica",
    "FRAME_FLUID_PARAMS": "Parámetros de Fluido",
    "FRAME_BARRIER_PARAMS": "Parámetros de Barrera",
    "FRAME_ANIMATION_PARAMS": "Parámetros de Animación",
    "LBL_INFLOW_VELOCITY": "Velocidad de Flujo:",
    "LBL_VISCOSITY": "Viscosidad:",
    "LBL_BARRIER_PRESET": "Preajuste de Barrera:",
    "LBL_ANIMATION_TYPE": "Tipo de Animación:",
    "LBL_ANIMATION_SPEED": "Velocidad de Animación:",
    "LBL_CONTRAST": "Contraste:",
    "CHK_CHANGEABLE_BARRIER": "Barrera Erosionable",
    "CHART_X_AXIS": "Generación",
    "CHART_Y_AXIS": "Fuerza",
    "LIFT": "Levantamiento",
    "DRAG": "Arrastre",
    "CHART_TITLE": "Curva Fuerza-Generación",
    "MSG_INVALID_INPUT_TITLE": "Entrada Inválida",
    "MSG_INVALID_INPUT_BODY": "Por favor ingrese un número entre 50 y 999.",
    "MSG_BARRIER_CHANGED_ILLEGALLY": "ADVERTENCIA: BARRERA EN CAMBIO ILEGAL",
    "LBL_T_START": "Valor inicial de t:",
    "LBL_T_END": "Valor final de t:",
    "LBL_CALC_PRECISION": "Precisión de Cálculo:",
    "BTN_CONFIRM": "Confirmar",
    "BTN_DEFAULT_PARAMS": "Parámetros Predeterminados",
    "CHK_AUTO_UPDATE": "Actualización Automática",
    "BTN_MOUSE_DRAW": "Ratón: Dibujar",
    "BTN_MOUSE_ERASE": "Ratón: Borrar",
    "BTN_CLEAR_BARRIER": "Limpiar Barrera",
    "LBL_LATTICE_HEIGHT": "Altura de la Red:",
    "LBL_LATTICE_WIDTH": "Ancho de la Red:",
    "BTN_CANCEL": "Cancelar",
    "WIN_TITLE_SAVE": "Guardar",
    "WIN_TITLE_OPEN": "Abrir",
    "WIN_TITLE_SAVE_IMG": "Guardar como Imagen",
    "FILE_TYPE_LBM": "Archivo de Proyecto LBM",
    "FILE_TYPE_IMG": "Archivo de Imagen",
    "MENU_FILE": "Archivo",
    "MENU_NEW": "Nuevo",
    "MENU_OPEN": "Abrir",
    "MENU_SAVE": "Guardar",
    "MENU_SCREENSHOT": "Captura de Pantalla",
    "MENU_SCREENSHOT_AS": "Captura de Pantalla Como",
    "MENU_EXIT": "Salir",
    "MENU_OPERATION": "Operación",
    "MENU_START": "Inicio",
    "MENU_PAUSE": "Pausa",
    "MENU_NEXT_GEN": "Siguiente Generación",
    "MENU_NEXT_10_GEN": "Siguiente 10 Gen",
    "MENU_NEXT_100_GEN": "Siguiente 100 Gen",
    "MENU_NEXT_1000_GEN": "Siguiente 1000 Gen",
    "MENU_RESET_PARAMS": "Restablecer Parámetros",
    "MENU_VIEW": "Vista",
    "MENU_ANIM_CURL": "Animación de Curvatura",
    "MENU_ANIM_DENSITY": "Animación de Densidad",
    "MENU_ANIM_STREAMLINE": "Líneas de Corriente",
    "MENU_ANIM_VELOCITY_VECTOR": "Vector de Velocidad",
    "MENU_ANIM_HORIZONTAL_VELOCITY": "Velocidad Horizontal",
    "MENU_ANIM_VERTICAL_VELOCITY": "Velocidad Vertical",
    "MENU_CHART_LIFT_DRAG": "Gráfico de Elevación-Arrastre",
    "MENU_ADVANCED": "Avanzado",
    "MENU_LATTICE_FMT": "Red: {}x{}",
    "MENU_CUSTOM_LATTICE": "Tamaño de Red Personalizado",
    "MENU_BOUNCE_WIND_TUNNEL": "Rebote: Túnel de Viento (Arriba/Abajo)",
    "MENU_BOUNCE_NO": "Rebote: Ninguno",
    "MENU_BOUNCE_THREE_SIDE": "Rebote: Tres Lados",
    "MENU_BOUNCE_CAVITY": "Rebote: Cavidad (Todos los Lados)",
    "MENU_ABOUT": "Acerca de",
    "MENU_HELP": "Ayuda",
    "BTN_CLEAR_CURVE": "Limpiar",
    "CHK_AUTO_UPDATE_CURVE": "Auto Actualizar",
    "BTN_UPDATE_BARRIER": "Actualizar Barrera",
    "MENU_LANGUAGE": "Idioma",
    "MENU_LANG_ZH": "Chino",
    "MENU_LANG_EN": "Inglés",
    "MENU_LANG_ES": "Español"
}
