# -*- coding: utf-8 -*-

LANG_EN = {
    "APP_TITLE": "LBM Fluid Simulator",
    "BTN_PAUSE": "Pause",
    "BTN_START": "Start",
    "BTN_NEXT_FRAME": "Next Frame",
    "BTN_RESET": "Reset",
    "BTN_IMPORT": "Open",
    "BTN_EXPORT": "Save",
    "BTN_ADVANCED_BARRIER": "Advanced Barrier",
    "FRAME_BASIC_INFO": "Basic Info",
    "FRAME_FLUID_PARAMS": "Fluid Params",
    "FRAME_BARRIER_PARAMS": "Barrier Params",
    "FRAME_ANIMATION_PARAMS": "Animation Params",
    "LBL_INFLOW_VELOCITY": "Inflow Velocity:",
    "LBL_VISCOSITY": "Viscosity:",
    "LBL_BARRIER_PRESET": "Barrier Preset:",
    "LBL_ANIMATION_TYPE": "Animation Type:",
    "LBL_ANIMATION_SPEED": "Animation Speed:",
    "LBL_CONTRAST": "Contrast:",
    "CHK_CHANGEABLE_BARRIER": "Erodible Barrier",
    "CHART_X_AXIS": "Generation",
    "CHART_Y_AXIS": "Force",
    "LIFT": "Lift",
    "DRAG": "Drag",
    "CHART_TITLE": "Force-Generation Curve",
    "MSG_INVALID_INPUT_TITLE": "Invalid Input",
    "MSG_INVALID_INPUT_BODY": "Please enter a number between 50 and 999.",
    "MSG_BARRIER_CHANGED_ILLEGALLY": "WARNING: BARRIER CHANGED ILLEGALLY",
    "LBL_T_START": "t start value:",
    "LBL_T_END": "t end value:",
    "LBL_CALC_PRECISION": "Calculation Precision:",
    "BTN_CONFIRM": "Confirm",
    "BTN_DEFAULT_PARAMS": "Default Params",
    "CHK_AUTO_UPDATE": "Auto Update",
    "BTN_MOUSE_DRAW": "Mouse: Draw",
    "BTN_MOUSE_ERASE": "Mouse: Erase",
    "BTN_CLEAR_BARRIER": "Clear Barrier",
    "LBL_LATTICE_HEIGHT": "Lattice Height:",
    "LBL_LATTICE_WIDTH": "Lattice Width:",
    "BTN_CANCEL": "Cancel",
    "WIN_TITLE_SAVE": "Save",
    "WIN_TITLE_OPEN": "Open",
    "WIN_TITLE_SAVE_IMG": "Save to Image",
    "FILE_TYPE_LBM": "LBM Project File",
    "FILE_TYPE_IMG": "Image File",
    "MENU_FILE": "File",
    "MENU_NEW": "New",
    "MENU_OPEN": "Open",
    "MENU_SAVE": "Save",
    "MENU_SCREENSHOT": "Screenshot",
    "MENU_SCREENSHOT_AS": "Screenshot As",
    "MENU_EXIT": "Exit",
    "MENU_OPERATION": "Operation",
    "MENU_START": "Start",
    "MENU_PAUSE": "Pause",
    "MENU_NEXT_GEN": "Next Gen",
    "MENU_NEXT_10_GEN": "Next 10 Gen",
    "MENU_NEXT_100_GEN": "Next 100 Gen",
    "MENU_NEXT_1000_GEN": "Next 1000 Gen",
    "MENU_RESET_PARAMS": "Reset Params",
    "MENU_VIEW": "View",
    "MENU_ANIM_CURL": "Curl Animation",
    "MENU_ANIM_DENSITY": "Density Animation",
    "MENU_ANIM_STREAMLINE": "Streamline",
    "MENU_ANIM_VELOCITY_VECTOR": "Velocity Vector",
    "MENU_ANIM_HORIZONTAL_VELOCITY": "Horizontal Velocity",
    "MENU_ANIM_VERTICAL_VELOCITY": "Vertical Velocity",
    "MENU_CHART_LIFT_DRAG": "Lift-Drag Chart",
    "MENU_ADVANCED": "Advanced",
    "MENU_LATTICE_FMT": "Lattice: {}x{}",
    "MENU_CUSTOM_LATTICE": "Custom Lattice Size",
    "MENU_BOUNCE_WIND_TUNNEL": "Bounce: Wind Tunnel (Top/Bottom)",
    "MENU_BOUNCE_NO": "Bounce: None",
    "MENU_BOUNCE_THREE_SIDE": "Bounce: Three Sides",
    "MENU_BOUNCE_CAVITY": "Bounce: Cavity (All Sides)",
    "MENU_ABOUT": "About",
    "MENU_HELP": "Help",
    "BTN_CLEAR_CURVE": "Clear",
    "CHK_AUTO_UPDATE_CURVE": "Auto Update",
    "BTN_UPDATE_BARRIER": "Update Barrier",
    "MENU_LANGUAGE": "Language",
    "MENU_LANG_ZH": "Chinese",
    "MENU_LANG_EN": "English",
    "MENU_LANG_ES": "Spanish"
}
