# -*- coding: utf-8 -*-

LANG_ZH = {
    "APP_TITLE": "LBM流体模拟器",
    "BTN_PAUSE": "暂停",
    "BTN_START": "开始",
    "BTN_NEXT_FRAME": "下一帧",
    "BTN_RESET": "重置",
    "BTN_IMPORT": "打开",
    "BTN_EXPORT": "保存",
    "BTN_ADVANCED_BARRIER": "高级障碍",
    "FRAME_BASIC_INFO": "基本信息",
    "FRAME_FLUID_PARAMS": "流动参数",
    "FRAME_BARRIER_PARAMS": "障碍参数",
    "FRAME_ANIMATION_PARAMS": "动画参数",
    "LBL_INFLOW_VELOCITY": "来流速度：",
    "LBL_VISCOSITY": "粘性系数：",
    "LBL_BARRIER_PRESET": "障碍预设：",
    "LBL_ANIMATION_TYPE": "动画类型：",
    "LBL_ANIMATION_SPEED": "动画速度：",
    "LBL_CONTRAST": "对比程度：",
    "CHK_CHANGEABLE_BARRIER": "可变障碍",
    "CHART_X_AXIS": "代数",
    "CHART_Y_AXIS": "力",
    "LIFT": "升力",
    "DRAG": "阻力",
    "CHART_TITLE": "力-代数 曲线",
    "MSG_INVALID_INPUT_TITLE": "请输入符合要求的数值",
    "MSG_INVALID_INPUT_BODY": "输入范围限制在[50,999]，仅数字",
    "MSG_BARRIER_CHANGED_ILLEGALLY": "WARNING: BARRIER CHANGED ILLEGALLY",
    "LBL_T_START": "t的起始值:",
    "LBL_T_END": "t的终止值:",
    "LBL_CALC_PRECISION": "计算精度：",
    "BTN_CONFIRM": "确定",
    "BTN_DEFAULT_PARAMS": "默认参数",
    "CHK_AUTO_UPDATE": "自动更新",
    "BTN_MOUSE_DRAW": "鼠标：绘制",
    "BTN_MOUSE_ERASE": "鼠标：擦除",
    "BTN_CLEAR_BARRIER": "清除障碍",
    "LBL_LATTICE_HEIGHT": "格子高度：",
    "LBL_LATTICE_WIDTH": "格子宽度：",
    "BTN_CANCEL": "取消",
    "WIN_TITLE_SAVE": "保存",
    "WIN_TITLE_OPEN": "导入",
    "WIN_TITLE_SAVE_IMG": "保存到图片",
    "FILE_TYPE_LBM": "格子-玻尔兹曼 工程文件",
    "FILE_TYPE_IMG": "图片文件",
    "MENU_FILE": "文件",
    "MENU_NEW": "新建",
    "MENU_OPEN": "打开",
    "MENU_SAVE": "保存",
    "MENU_SCREENSHOT": "截图",
    "MENU_SCREENSHOT_AS": "截图为",
    "MENU_EXIT": "退出",
    "MENU_OPERATION": "操作",
    "MENU_START": "开始",
    "MENU_PAUSE": "暂停",
    "MENU_NEXT_GEN": "下一代",
    "MENU_NEXT_10_GEN": "下十代",
    "MENU_NEXT_100_GEN": "下百代",
    "MENU_NEXT_1000_GEN": "下千代",
    "MENU_RESET_PARAMS": "重置参数",
    "MENU_VIEW": "查看",
    "MENU_ANIM_CURL": "旋度动画",
    "MENU_ANIM_DENSITY": "密度动画",
    "MENU_ANIM_STREAMLINE": "流线",
    "MENU_ANIM_VELOCITY_VECTOR": "速度矢量",
    "MENU_ANIM_HORIZONTAL_VELOCITY": "水平速度",
    "MENU_ANIM_VERTICAL_VELOCITY": "垂直速度",
    "MENU_CHART_LIFT_DRAG": "升力阻力-代数 图",
    "MENU_ADVANCED": "高级",
    "MENU_LATTICE_FMT": "格子规格：{}x{}",
    "MENU_CUSTOM_LATTICE": "自定义格子规格",
    "MENU_BOUNCE_WIND_TUNNEL": "反弹格式：风洞（上下反弹）",
    "MENU_BOUNCE_NO": "反弹格式：无反弹",
    "MENU_BOUNCE_THREE_SIDE": "反弹格式：三侧反弹",
    "MENU_BOUNCE_CAVITY": "反弹格式：方腔流（全侧反弹）",
    "MENU_ABOUT": "关于",
    "MENU_HELP": "帮助",
    "BTN_CLEAR_CURVE": "清除曲线",
    "CHK_AUTO_UPDATE_CURVE": "自动刷新曲线",
    "BTN_UPDATE_BARRIER": "更新障碍",
    "MENU_LANGUAGE": "语言",
    "MENU_LANG_ZH": "中文",
    "MENU_LANG_EN": "English",
    "MENU_LANG_ES": "Español"
}
